### ISSUE TITLE
Auth0 Login -> DB -> render to profile successfully

### ISSUE THREAD

**Issue by Jorge-Cano** [wdi-atx-10/class#9]
I'm having trouble connecting the Login functionality to the Database, and render back to Profile. 
Could I please, have someone help me in person. I'm able to follow Growler/Todo to make this happen so far..

**Comment by dirkdunn** [comment]
Alright, connecting login functionality to the database, so what is it you are trying to achieve? 

Do you mean setting up authentication with Auth0?

**Comment by Jorge-Cano** [comment]
Yes, Setting up pretty much. I initially started with Multi-Page then switched to SPA... I don't know if there are conflicting bits of code, but I'm running through the full Steps of Set Up and everything seems to be there, but continues to crash and throw errors.

**Comment by Jorge-Cano** [comment]
/Users/aleissia/code/wdi/wdi-atx-10/project/EasyRide_Dev/backend/app.js:24
var lock = new Auth0Lock('cQGdAfq6ZAF2BZuLRx1TDrmU4D9NrhCU', 'jacinaustin.auth0.com');
               ^

ReferenceError: Auth0Lock is not defined
    at Object.<anonymous> (/Users/aleissia/code/wdi/wdi-atx-10/project/EasyRide_Dev/backend/app.js:24:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/aleissia/code/wdi/wdi-atx-10/project/EasyRide_Dev/backend/bin/www:7:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:422:7)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by dirkdunn** [comment]
Check Slack regarding the answer to this, but continue to post on here
